#!/bin/bash

cd `dirname "${BASH_SOURCE[0]}"`
cd ..
browserify index.js -o browser/fullnode.js
browserify -g uglifyify index.js -o browser/fullnode-min.js
find test/ -type f -name "*.js" | xargs browserify -o browser/tests.js
